### ISSUE TITLE
Feinne Class on Grasta Screen Incorrect

### ISSUE THREAD

**Issue by veratos** [BeaverHouse/aecheck-v3#10]
### Current behavior

Should be Exalted Maiden & not Noble Maiden

### Steps to reproduce

Search Feinne on Grasta Screen

**Comment by veratos** [comment]
Melody AS Class should be Medea & not Medeia

**Comment by veratos** [comment]
Miyu NS Class Should be Princess & not Rune Knight

**Comment by veratos** [comment]
Red Clad Flam.(NS) should be named Dewey

**Comment by veratos** [comment]
Riica Class should be Gratinel & not Patriarch

**Comment by veratos** [comment]
Silver Striker(NS) should be named Premaya

**Comment by veratos** [comment]
Violet Lancer(NS) should be named Toova

**Comment by HU-Lee** [comment]
**AC characters in the future mythos is not unveiled at first, so it must be hidden.**
It follows https://anothereden.wiki/w/Characters

**Comment by HU-Lee** [comment]
Others were checked:
- https://anothereden.wiki/w/Gratinel_Psalm
- https://anothereden.wiki/w/Princess_Psalm
- https://anothereden.wiki/w/Medea_Treatise
- https://youtu.be/9AclqbN5BWE?feature=shared
    - There's inconsistency in https://anothereden.wiki/w/Feinne  
      and you're correct.

**Comment by HU-Lee** [comment]
Resolved with PR #11
