### ISSUE TITLE
Tiramisu Manifest missing

### ISSUE THREAD

**Issue by Ilya0S** [BeaverHouse/aecheck-v3#15]
### Category

Content/Data report

### Detailed description

It was added along with her SA. Normal manifest, not true one. SA was added, but not manifest.
Did I choose right options (request, contend/data report)?

**Comment by HU-Lee** [comment]
Ok I forgot this. 
I'll add it in a day because I'm currently working now

PS. 
You did right on writing the issue. 🚀
You don't have to consider all the time because I konw that normal users cannot distinguish the category properly :)

**Comment by HU-Lee** [comment]
Resolved with #16.
