### ISSUE TITLE
**AC characters in the future mythos is not unveiled at first, so it must be hidden.**

### ISSUE THREAD

**Issue by veratos** [BeaverHouse/aecheck-v3#17]
**AC characters in the future mythos is not unveiled at first, so it must be hidden.**
It follows https://anothereden.wiki/w/Characters

_Originally posted by @HU-Lee in https://github.com/BeaverHouse/aecheck-v3/issues/10#issuecomment-1962942631_

**Comment by veratos** [comment]
![image](https://github.com/BeaverHouse/aecheck-v3/assets/27906065/93f07278-06e9-42ec-90c9-b8a771b60d34)
What's with the inconsistency? If you can do this for this char, why you can't do for others?

**Comment by Ilya0S** [comment]
Alter Dunarith, along with other non-mythos alter characters, reveals his name during his first CQ which is available even without owning him. If you learn his name just after meeting him, how is it a spoiler?
The only alter character whom we meet in any kind of story (aside from future mythos), and not only in their CQ, is Tsukiha. And again, she tells her name immediately, both in CQ and Apocrypha chapter, whichever you complete first.

Meanwhile, for future mythos, the ambiguity is there for a reason. Toova being seen as Suzette is a big thing in the story, then Dewey looking way older than og Dewey, and so on.

For that reason, I support HU-Lee's decision on covering their names. And I hope they'll do the same if some other character will appear whose name will be revealed at a later point in story. E.g. if Poporo is getting a 5* upgrade one day, I hope he will be named Nopaew in this checklist.

Also, I'll ask wiki admins about this, there may not be any reason to keep the spoiler tags at non-mythos characters. Maybe it's a matter of convenience though, with it coded into all alter characters back when mythos released.

**Comment by veratos** [comment]
Thanks for the information. My point is still valid.
![image](https://github.com/BeaverHouse/aecheck-v3/assets/27906065/9583a8f0-13a3-46ca-991a-a061adad4163)
The names supposedly follow wiki char list but this particular record did not.

While I agree with you, it all boils down to whether players have cleared the free content or not right?

**Comment by Ilya0S** [comment]
Checked in with wiki admins - as I suspected, it's just the case of it being coded this way from the beginning, and character pages already having too many fields to make one just to separate alters in some way. Aecheck doesn't have such concerns as "too many fields", so it can do it its own way. It's not obligated to copy the wiki in every single thing.

It's not this particular record, but all the alters except for future mythos characters. And no, it doesn't boil down to whether players have cleared the free content or not.
It boils down to how fast players can get to said free content. For non-mythos ones, it's "Clear chapter 11-20". Hardly anyone comes at web resources before clearing part 1 of main story, so no-spoilers rules* don't apply to content there, including sidequests and character quests that everyone has access to (those of free characters and cq1 of alters). Basically, this stuff can be accessed on the player's first or second day of playing easily.
For mythos itself, it's:
- Clear chapter 25
- Clear IDA 1
- Clear chapter 44 for C2
- Clear IDA 3 for C2
- Clear Azure Rebel for C4
- Clear chapter 60 for C5
- Clear chapter 75 for C6

And for alters from Mythos, you need to clear specific chapters of Mythos to unlock their 1st cq.

As you can see, there's way more content in the way. First, it requires full clear of part 1 just to start, which already stops exempting it from no-spoilers rules. Second, it requires fully clearing an episode. Third, it only gives you access to one chapter where you only learn black Isuka's name, and the rest need even more things to clear to learn their names. It would take most players at least a week to start chapter 2, and I think it could take months to get to the end without rushing.

\* No-spoilers rules I mentioned are the ones that are used throughout the AE community, i.e. in its primary global discord server and subreddit.

------------

### An actual inconsistency:
However, there is another issue I noticed while checking all this: while the rest of the alters have just their names (or alias for future mythos ones), **_Shion is named as "Shion (Alter)"_**, which means either he has to get "(Alter)" removed, or everyone else has to get it added.

**Comment by HU-Lee** [comment]
1. https://anothereden.wiki/w/Dream_Weaver
2. https://anothereden.wiki/w/Dunarith_(Alter)

Both goes to the same link. Link 1 is redirected to Link 2.

All these 2 links are valid, so it dosen't have to make more mappings to alter characters who reveals their name immediately, from the announcement to in-game content.

Exceptions are the characters from future mythos, as mentioned above.

Of course I can unify all AC charaters to both `(Alter)` or `Violet Lancer, Dream Weaver...` but both will make a complaint for me:
- If I choose the first, _Why you didn't hide the important spoiler from future mythos or sth_
- And others like you, _Dream Weaver is wrong or hard to search, I just want "Dunarith"_

**This is a middle ground that I found, and I have no reason to change this rule because of a particular user's complaint.**  

And strictly speaking, it's totally wrong that I violated the wiki rule.  
The table is written in **Dream Weaver** but It finally goes to **https://anothereden.wiki/w/Dunarith_(Alter)**, can you confidently say that the first one is right?

<br>

Only I need to change is to modify Shion's display name as @Ilya0S mentioned.

**Comment by HU-Lee** [comment]
> ### An actual inconsistency:
> However, there is another issue I noticed while checking all this: while the rest of the alters have just their names (or alias for future mythos ones), **_Shion is named as "Shion (Alter)"_**, which means either he has to get "(Alter)" removed, or everyone else has to get it added.

![image](https://github.com/BeaverHouse/aecheck-v3/assets/74810034/7f67e03c-9789-438a-a26a-c5cc27541457)

There was a spacing issue and it's fixed with v3.6.0 update.
