### ISSUE TITLE
Melina's SA missing; True Manifest added but Bertrand's is still highlighted as the newest

### ISSUE THREAD

**Issue by Ilya0S** [BeaverHouse/aecheck-v3#30]
### Current behavior

All in the title

### Steps to reproduce

Open respective menus

### Other information

I don't really understand why this template is necessary, most of the reports here wouldn't need steps to reproduce and current/expected behaviours, just descriptions. But I guess it's Github's problem.

**Comment by HU-Lee** [comment]
This template is shown because you selected bug report.
Bug report is about something malfuctioning like website crash, not content missing issues.

And also, GitHub Issue is the place for discussing something about code, not a customer service center.
I don't think that it's wrong.

**Comment by HU-Lee** [comment]
I'll fix this in a day btw
