### ISSUE TITLE
Support more filter options

### ISSUE THREAD

**Issue by nhhai** [BeaverHouse/aecheck-v3#35]
### Category

Feature request

### Detailed description

First, thank you for the great checking tool you selflessly create for others. I've been using it since the old version.
What I found the new version lack compares to the old version is a way to filter out completed weapon manifest and special grastas from the view.

In the old version, after completing a weapon manifest and special grastas, it would move to the completed session. I found this gives an extremely satisfying feeling when I complete one and see the huge list shrinks. The new view doesn't accomplish this imo.

I believe a common way to use this tool for many people are as following:
- In `Character` page, show only the characters that they don't currently own.
- In `Manifest`, `Grasta` and `Awaken` pages, show the characters that they owned, but optionally show / hide the ones that they completed the progress.

With the above use case in mind, I suggestions the following changes:
- Use different filter state for each page. As you can see, the `Character` and the other pages' filters usually conflicts. While in the `Character` you usually show what you don't own, it's completely the opposite the other pages. I must say that the old behavior is better than the current.
- Support filters that are related to completion progress like in the old version. (e.g: awakening state, grasta, manifest...)

I haven't read the code but I think it shouldn't be too hard and can submit a PR myself. Just following the guide and start a discussion first.

**Comment by HU-Lee** [comment]
Hello, thanks for the suggestion.

For example (it's not strictly correct just for sample)
- In `Character` section, default filter for not owned characters
- In `Manifest` section, default filter for characters that manifest is not completed
- ...

Do I understand your opinion correctly?
If it does, the first task may not be too hard, but I need to find out for the second task that how much it takes to.

**Comment by nhhai** [comment]
Correct.
However, I noticed that the biggest different in v3 is that you were trying to make a universal view. Therefore, I think the easiest way is to extend the filter panel, the idea is as the following image:
![image](https://github.com/user-attachments/assets/d43f88f0-ada3-44f4-9757-71c1491f0999)

I'm not sure how you're storing the current filter state, I suppose you're using local storage for that. Therefore, I suggest instead of making all 4 tabs using the same storage keys, we separate them into 4 different states.

This way, you keep the universal filtering UI, and simply have one state for each page. I think it's the easiest way to achieve the above suggestion.

**Comment by nhhai** [comment]
A bit more details, maybe you add a certain prefix when loading each page, and add that prefix into all the keys that you use to store all the filtering options?

**Comment by HU-Lee** [comment]
Ah, okay.
I'm planning to improve this website step by step, so I'll add this to the task.

It'll require more work if this format of UI is added, so let me open this issue for a while.

**Comment by HU-Lee** [comment]
@nhhai

https://dev.aecheck.com/check
It's still on the development, but I think it's nearly done enough to this issue.

Update this issue if you have any opinions, and I'll keep this issue open until the release.

![image](https://github.com/user-attachments/assets/c360803f-5fdd-4990-9f59-24472e211a45)

PS. I'll fix the align issue @.@

**Comment by nhhai** [comment]
This looks perfect. Exactly what I think it should be.

I would suggest using tabs for the right panel though. Three rows with scrollbar looks narrow and I think people rarely look at all three at once. Using tabs we can save much more space for displaying the characters.

The `Not Owned` filter on the Manifest is also extremely useful to have on others as well, but I think you already plan on adding it.

Again, thank you for your awesome work.

**Comment by HU-Lee** [comment]
`Not owned` filters for the rest need to be independent with current filters, because the users may have grasta or stellar awakening materials of characters although they do not own the character itself.

I think the space to add this filters can be made when I change it to the right-side tab.

Updates may be slow because I didn't have enough time this week, but I'll try to update ASAP.

**Comment by HU-Lee** [comment]
https://dev.aecheck.com/check

It's separated to tabs,
I used horizontal tab because it is hard to position Mobile UI when using right tab.

After some other checks, I'm planning to announce so that it can be tested on public.

**Comment by nhhai** [comment]
It looks great on my 6" Android phone, and functionality wise it's been working well so far, it's much easier to use than the current version.

One thing though: currently if the `Not Owned`, `Class Change Required` and `Owned` setting is shared across all 3 tabs (`Owned State`, `Grasta` and `SA`). However, it's ok to keep it as is because it's very easy to use now compared to before, I simply need check / uncheck the `Owned` setting.

**Comment by HU-Lee** [comment]
Yes, the owned state is configured as global and stored in a web cache.

I considered it for a while, it has pros and cons, and I think it's ok to set it as-is right now. 😅

Okay I'll keep on working based on this proto type :)
Thanks for the suggestion.

**Comment by HU-Lee** [comment]
This feature was finally merged with v3.1
