### ISSUE TITLE
Altena's grasta missing

### ISSUE THREAD

**Issue by Ilya0S** [BeaverHouse/aecheck-v3#37]
### Category

Content/Data report

### Detailed description

Altena's (Beast Princess) grasta was added alongside Feinne's (The Renewed) several versions ago. Just noticed it's not at the site currently.

**Comment by HU-Lee** [comment]
I checked it from https://www.anothereden.wiki/w/Grasta_VC

Thanks for the report, it will be included with the next release.

**Comment by HU-Lee** [comment]
Resolved with #38
