### ISSUE TITLE
Cerrine AS missing from Grasta Page

### ISSUE THREAD

**Issue by veratos** [BeaverHouse/aecheck-v3#9]
### Current behavior

Cerrine AS missing from Grasta Page

### Expected behavior

Cerrine AS exist in Grasta Page

### Steps to reproduce

https://aecheck.com/check/grasta
Cerrine AS not listed here

**Comment by veratos** [comment]
Gariyu AS also missing

**Comment by HU-Lee** [comment]
Hello.

Grasta checker is extended from Dungeon drop list in previous version,
so free character's grasta is absent now.

I have to wrap up the list of the VC grasta data (including non-English i18n info)
so it'll be take a while to be resolved

**Comment by veratos** [comment]
Ok noted

**Comment by HU-Lee** [comment]
Updated by https://github.com/BeaverHouse/aecheck-data/pull/7

Following character's VC Grasta is not identified:
- https://anothereden.wiki/w/Gariyu_(Another_Style)
- (NS) https://anothereden.wiki/w/Levia
- (NS) https://anothereden.wiki/w/Clarte
- https://anothereden.wiki/w/Prai
- (NS) https://anothereden.wiki/w/Noahxis
- https://anothereden.wiki/w/Strawboy_(Blunt)
- https://anothereden.wiki/w/Altena
- https://anothereden.wiki/w/Uquaji
- (NS) https://anothereden.wiki/w/Nona

If you think the update data is not valid,
**please report with evidence that supports it.
(ex. screenshots, video, wiki link)**

I'm not playing AE now and I cannot accept the issue if I cannot check information from some references.

**Comment by veratos** [comment]
NS Clarte
[https://anothereden.wiki/w/Clarte](https://anothereden.wiki/w/Clarte)
![image](https://github.com/BeaverHouse/aecheck-v3/assets/27906065/18632b28-440a-4f30-9521-595242e3328a)

Checked others no VC Grasta yet. After adding this, can close this ticket.

**Comment by HU-Lee** [comment]
Moonlit Guidance doesn't enhance character's Valor Chant so it's excluded.

**Comment by veratos** [comment]
Ok fair enough. Closing this ticket.
